x-spring-prod: &spring-prod
  environment:
    DB_HOST: ${AWS_RDS_ENDPOINT}
    DB_PORT: 3306
    DB_NAME: ${DB_NAME:-dbeduclear}
    DB_USER: ${DB_USER}
    DB_PASSWORD: ${DB_PASSWORD}
    SPRING_DATASOURCE_URL: jdbc:mariadb://${AWS_RDS_ENDPOINT}:3306/${DB_NAME:-dbeduclear}?sslMode=trust
    SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 2
    SPRING_JPA_HIBERNATE_DDL_AUTO: update
    SPRING_JPA_SHOW_SQL: "false"

services:
  api-gateway:
    ports:
      - "8080:8080"
    <<: *spring-prod
    restart: always

  usuario-service:
    <<: *spring-prod
    restart: always

  curso-service:
    <<: *spring-prod
    restart: always

  asignatura-service:
    <<: *spring-prod
    restart: always

  materiales-service:
    <<: *spring-prod
    restart: always

  frontend:
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always