x-db-env: &db-env
  DB_NAME: ${DB_NAME}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}

services:
  api-gateway:
      build: ./educlear-service-Backend/gateway-educlear

  usuario-service:
    build: ./educlear-service-Backend/usuario-service
    environment:
      <<: *db-env

  curso-service:
    build: ./educlear-service-Backend/curso-service
    environment:
      <<: *db-env

  asignatura-service:
    build: ./educlear-service-Backend/asignatura-service
    environment:
      <<: *db-env

  materiales-service:
    build: ./educlear-service-Backend/materiales-service
    environment:
      <<: *db-env

  frontend:
    build: ./educlear-frontend