services:
  mariadb:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${PORT_MARIADB}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./basedatoseduclear.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  usuario-service:
    # Usamos la etapa de 'build' del Dockerfile porque contiene Maven
    build:
      context: ./educlear-service-Backend/usuario-service
      target: build
    ports:
      - "${PORT_USUARIO}:8080"
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306 # Puerto interno de la red Docker
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./educlear-service-Backend/usuario-service:/app
    # Este comando arranca Spring Boot y queda escuchando cambios en el código
    entrypoint: mvn spring-boot:run
    depends_on:
      mariadb:
        condition: service_healthy

  curso-service:
    build:
      context: ./educlear-service-Backend/curso-service
      target: build
    ports:
      - "${PORT_CURSO}:8081"
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./educlear-service-Backend/curso-service:/app
    entrypoint: mvn spring-boot:run
    depends_on:
      mariadb:
        condition: service_healthy

    asignatura-service:
    build:
      context: ./educlear-service-Backend/asignatura-service
      target: build
    ports:
      - "${PORT_ASIGNATURA}:8082"
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./educlear-service-Backend/curso-service:/app
    entrypoint: mvn spring-boot:run
    depends_on:
      mariadb:
        condition: service_healthy

    materiales-service:
    build:
      context: ./educlear-service-Backend/materiales-service
      target: build
    ports:
      - "${PORT_MATERIALES}:8083"
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./educlear-service-Backend/curso-service:/app
    entrypoint: mvn spring-boot:run
    depends_on:
      mariadb:
        condition: service_healthy

  frontend:
      build:
        context: ./educlear-frontend
        target: build
      ports:
        - "${PORT_FRONTEND}:80"
      volumes:
        - ./educlear-frontend:/app
        # Este volumen anónimo evita que los node_modules de tu Windows 
        # sobrescriban a los del contenedor, evitando conflictos de SO
        - /app/node_modules
      # Instalamos el CLI, las dependencias y arrancamos
      entrypoint: >
        sh -c "npm install -g @angular/cli && 
              npm install --legacy-peer-deps && 
              npx ng serve --host 0.0.0.0 --port 80 --disable-host-check --poll 2000"

volumes:
  mariadb_data: