services:
  # El GATEWAY es el único que expone puertos al exterior (80 o 9000)
  api-gateway:
    image: tu-usuario-docker/gateway-educlear:latest
    ports:
      - "80:8080" # Mapeamos el puerto 80 de la EC2 al 8080 del Gateway
    restart: always

  usuario-service:
    # Usaremos la imagen ya compilada en Docker Hub o ECR
    image: tu-usuario-docker/usuario-service:latest 
    environment:
      # Estos valores apuntarán al Endpoint de AWS RDS en el .env de la EC2
      DB_HOST: ${AWS_RDS_ENDPOINT} 
      DB_PORT: 3306
    restart: always

  curso-service:
    image: tu-usuario-docker/curso-service:latest
    environment:
      DB_HOST: ${AWS_RDS_ENDPOINT}
      DB_PORT: 3306
    restart: always

  asignatura-service:
    image: tu-usuario-docker/asignatura-service:latest
    environment:
      DB_HOST: ${AWS_RDS_ENDPOINT}
      DB_PORT: 3306
    restart: always

  materiales-service:
    image: tu-usuario-docker/materiales-service:latest
    environment:
      DB_HOST: ${AWS_RDS_ENDPOINT}
      DB_PORT: 3306
    restart: always

  frontend:
    image: tu-usuario-docker/frontend-tfg:latest
    ports:
      - "80:80"
    restart: always