x-db-env: &db-env
  DB_NAME: ${DB_NAME}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}

services:
  api-gateway:
    image: bianca0stam/gateway-educlear:latest

  usuario-service:
    image: bianca0stam/usuario-service:latest
    environment:
      <<: *db-env

  curso-service:
    image: bianca0stam/curso-service:latest
    environment:
      <<: *db-env

  asignatura-service:
    image: bianca0stam/asignatura-service:latest
    environment:
      <<: *db-env

  materiales-service:
    image: bianca0stam/materiales-service:latest
    environment:
      <<: *db-env

  frontend:
    image: bianca0stam/educlear-frontend:latest